# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Dock.create(section: 'east')
Dock.create(section: 'south')
Dock.create(section: 'west')
Dock.create(section: 'high_clamp')
Dock.create(section: 'clamp')
Dock.create(section: 'oe')
Dock.create(section: 'returns')
Dock.create(section: 'sail')

DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )
DoorRange.create(range: , dock_id: )









Door.create(number: 'D001', door_range_id: )
Door.create(number: 'D002', door_range_id: )
Door.create(number: 'D003', door_range_id: )
Door.create(number: 'D004', door_range_id: )
Door.create(number: 'D005', door_range_id: )
Door.create(number: 'D006', door_range_id: )
Door.create(number: 'D007', door_range_id: )
Door.create(number: 'D008', door_range_id: )
Door.create(number: 'D009', door_range_id: )
Door.create(number: 'D010', door_range_id: )
Door.create(number: 'D011', door_range_id: )
Door.create(number: 'D012', door_range_id: )
Door.create(number: 'D013', door_range_id: )
Door.create(number: 'D014', door_range_id: )
Door.create(number: 'D015', door_range_id: )
Door.create(number: 'D016', door_range_id: )
Door.create(number: 'D017', door_range_id: )
Door.create(number: 'D018', door_range_id: )
Door.create(number: 'D019', door_range_id: )
Door.create(number: 'D020', door_range_id: )
Door.create(number: 'D021', door_range_id: )
Door.create(number: 'D022', door_range_id: )
Door.create(number: 'D023', door_range_id: )
Door.create(number: 'D024', door_range_id: )
Door.create(number: 'D025', door_range_id: )
Door.create(number: 'D026', door_range_id: )
Door.create(number: 'D027', door_range_id: )
Door.create(number: 'D028', door_range_id: )
Door.create(number: 'D029', door_range_id: )
Door.create(number: 'D030', door_range_id: )
Door.create(number: 'D031', door_range_id: )
Door.create(number: 'D032', door_range_id: )
Door.create(number: 'D033', door_range_id: )
Door.create(number: 'D034', door_range_id: )
Door.create(number: 'D035', door_range_id: )
Door.create(number: 'D036', door_range_id: )
Door.create(number: 'D037', door_range_id: )
Door.create(number: 'D038', door_range_id: )
Door.create(number: 'D039', door_range_id: )
Door.create(number: 'D040', door_range_id: )
Door.create(number: 'D041', door_range_id: )
Door.create(number: 'D042', door_range_id: )
Door.create(number: 'D043', door_range_id: )
Door.create(number: 'D044', door_range_id: )
Door.create(number: 'D045', door_range_id: )
Door.create(number: 'D046', door_range_id: )
Door.create(number: 'D047', door_range_id: )
Door.create(number: 'D048', door_range_id: )
Door.create(number: 'D049', door_range_id: )
Door.create(number: 'D050', door_range_id: )
Door.create(number: 'D051', door_range_id: )
Door.create(number: 'D052', door_range_id: )
Door.create(number: 'D053', door_range_id: )
Door.create(number: 'D054', door_range_id: )
Door.create(number: 'D055', door_range_id: )
Door.create(number: 'D056', door_range_id: )
Door.create(number: 'D057', door_range_id: )
Door.create(number: 'D058', door_range_id: )
Door.create(number: 'D059', door_range_id: )
Door.create(number: 'D060', door_range_id: )
Door.create(number: 'D061', door_range_id: )
Door.create(number: 'D062', door_range_id: )
Door.create(number: 'D063', door_range_id: )
Door.create(number: 'D064', door_range_id: )
Door.create(number: 'D065', door_range_id: )
Door.create(number: 'D066', door_range_id: )
Door.create(number: 'D067', door_range_id: )
Door.create(number: 'D068', door_range_id: )
Door.create(number: 'D069', door_range_id: )
Door.create(number: 'D070', door_range_id: )
Door.create(number: 'D071', door_range_id: )
Door.create(number: 'D072', door_range_id: )
Door.create(number: 'D073', door_range_id: )
Door.create(number: 'D074', door_range_id: )
Door.create(number: 'D075', door_range_id: )
Door.create(number: 'D076', door_range_id: )
Door.create(number: 'D077', door_range_id: )
Door.create(number: 'D078', door_range_id: )
Door.create(number: 'D079', door_range_id: )
Door.create(number: 'D080', door_range_id: )
Door.create(number: 'D081', door_range_id: )
Door.create(number: 'D082', door_range_id: )
Door.create(number: 'D083', door_range_id: )
Door.create(number: 'D084', door_range_id: )
Door.create(number: 'D085', door_range_id: )
Door.create(number: 'D086', door_range_id: )
Door.create(number: 'D087', door_range_id: )
Door.create(number: 'D088', door_range_id: )
Door.create(number: 'D089', door_range_id: )
Door.create(number: 'D090', door_range_id: )
Door.create(number: 'D091', door_range_id: )
Door.create(number: 'D092', door_range_id: )
Door.create(number: 'D093', door_range_id: )
Door.create(number: 'D094', door_range_id: )
Door.create(number: 'D095', door_range_id: )
Door.create(number: 'D096', door_range_id: )
Door.create(number: 'D097', door_range_id: )
Door.create(number: 'D098', door_range_id: )
Door.create(number: 'D099', door_range_id: )
Door.create(number: 'D100', door_range_id: )
Door.create(number: 'D101', door_range_id: )
Door.create(number: 'D102', door_range_id: )
Door.create(number: 'D103', door_range_id: )
Door.create(number: 'D104', door_range_id: )
Door.create(number: 'D105', door_range_id: )
Door.create(number: 'D106', door_range_id: )
Door.create(number: 'D107', door_range_id: )
Door.create(number: 'D108', door_range_id: )
Door.create(number: 'D109', door_range_id: )
Door.create(number: 'D110', door_range_id: )
Door.create(number: 'D111', door_range_id: )
Door.create(number: 'D112', door_range_id: )
Door.create(number: 'D113', door_range_id: )
Door.create(number: 'D114', door_range_id: )
Door.create(number: 'D115', door_range_id: )
Door.create(number: 'D116', door_range_id: )