Dock.create(section: 'east')
Dock.create(section: 'south')
Dock.create(section: 'west')
Dock.create(section: 'high_clamp')
Dock.create(section: 'clamp')
Dock.create(section: 'oe')
Dock.create(section: 'returns')
Dock.create(section: 'sail')
Dock.create(section: 'fed-ex')


DoorRange.create(range: '1 - 4', dock_id: '6' )
DoorRange.create(range: '5 - 8', dock_id: '6')
DoorRange.create(range: '9 - 11', dock_id: '7')
DoorRange.create(range: '12 - 14', dock_id: '1')
DoorRange.create(range: '15 - 18', dock_id: '1')
DoorRange.create(range: '19 - 22', dock_id: '1')
DoorRange.create(range: '23 - 24', dock_id: '9')
DoorRange.create(range: '25 - 27', dock_id: '1')
DoorRange.create(range: '28 - 30', dock_id: '1')
DoorRange.create(range: '31 - 34', dock_id: '8')
DoorRange.create(range: '46 - 48', dock_id: '2')
DoorRange.create(range: '49 - 51', dock_id: '2')
DoorRange.create(range: '52 - 54', dock_id: '2')
DoorRange.create(range: '55 - 57', dock_id: '2')
DoorRange.create(range: '58 - 60', dock_id: '2')
DoorRange.create(range: '61 - 63', dock_id: '2')
DoorRange.create(range: '64 - 67', dock_id: '2')
DoorRange.create(range: '68 - 71', dock_id: '2')
DoorRange.create(range: '72 - 76', dock_id: '3')
DoorRange.create(range: '77 - 79', dock_id: '3')
DoorRange.create(range: '80 - 82', dock_id: '3')
DoorRange.create(range: '83 - 85', dock_id: '3')
DoorRange.create(range: '86 - 88', dock_id: '3')
DoorRange.create(range: '89 - 91', dock_id: '3')
DoorRange.create(range: '92 - 94', dock_id: '3')
DoorRange.create(range: '95 - 97', dock_id: '3')
DoorRange.create(range: '99 - 100', dock_id: '4')
DoorRange.create(range: '101 - 103', dock_id: '4')
DoorRange.create(range: '104 - 107', dock_id: '4')
DoorRange.create(range: '108 - 110', dock_id: '5')
DoorRange.create(range: '111 - 114', dock_id: '5')
DoorRange.create(range: '115 - 116', dock_id: '5')

Door.create(number: 'D001', door_range_id: '1')
Door.create(number: 'D002', door_range_id: '1')
Door.create(number: 'D003', door_range_id: '1')
Door.create(number: 'D004', door_range_id: '1')
Door.create(number: 'D005', door_range_id: '2')
Door.create(number: 'D006', door_range_id: '2')
Door.create(number: 'D007', door_range_id: '2')
Door.create(number: 'D008', door_range_id: '2')
Door.create(number: 'D009', door_range_id: '3')
Door.create(number: 'D010', door_range_id: '3')
Door.create(number: 'D011', door_range_id: '3')
Door.create(number: 'D012', door_range_id: '4')
Door.create(number: 'D013', door_range_id: '4')
Door.create(number: 'D014', door_range_id: '4')
Door.create(number: 'D015', door_range_id: '5')
Door.create(number: 'D016', door_range_id: '5')
Door.create(number: 'D017', door_range_id: '5')
Door.create(number: 'D018', door_range_id: '5')
Door.create(number: 'D019', door_range_id: '6')
Door.create(number: 'D020', door_range_id: '6')
Door.create(number: 'D021', door_range_id: '6')
Door.create(number: 'D022', door_range_id: '6')
Door.create(number: 'D023', door_range_id: '7')
Door.create(number: 'D024', door_range_id: '7')
Door.create(number: 'D025', door_range_id: '8')
Door.create(number: 'D026', door_range_id: '8')
Door.create(number: 'D027', door_range_id: '8')
Door.create(number: 'D028', door_range_id: '9')
Door.create(number: 'D029', door_range_id: '9')
Door.create(number: 'D030', door_range_id: '9')
Door.create(number: 'D031', door_range_id: '10')
Door.create(number: 'D032', door_range_id: '10')
Door.create(number: 'D033', door_range_id: '10')
Door.create(number: 'D034', door_range_id: '10')
## doesn't need in between doors
Door.create(number: 'D046', door_range_id: '11')
Door.create(number: 'D047', door_range_id: '11')
Door.create(number: 'D048', door_range_id: '11')
Door.create(number: 'D049', door_range_id: '12')
Door.create(number: 'D050', door_range_id: '12')
Door.create(number: 'D051', door_range_id: '12')
Door.create(number: 'D052', door_range_id: '13')
Door.create(number: 'D053', door_range_id: '13')
Door.create(number: 'D054', door_range_id: '13')
Door.create(number: 'D055', door_range_id: '14')
Door.create(number: 'D056', door_range_id: '14')
Door.create(number: 'D057', door_range_id: '14')
Door.create(number: 'D058', door_range_id: '15')
Door.create(number: 'D059', door_range_id: '15')
Door.create(number: 'D060', door_range_id: '15')
Door.create(number: 'D061', door_range_id: '16')
Door.create(number: 'D062', door_range_id: '16')
Door.create(number: 'D063', door_range_id: '16')
Door.create(number: 'D064', door_range_id: '17')
Door.create(number: 'D065', door_range_id: '17')
Door.create(number: 'D066', door_range_id: '17')
Door.create(number: 'D067', door_range_id: '17')
Door.create(number: 'D068', door_range_id: '18')
Door.create(number: 'D069', door_range_id: '18')
Door.create(number: 'D070', door_range_id: '18')
Door.create(number: 'D071', door_range_id: '18')
Door.create(number: 'D072', door_range_id: '19')
Door.create(number: 'D073', door_range_id: '19')
Door.create(number: 'D074', door_range_id: '19')
Door.create(number: 'D075', door_range_id: '19')
Door.create(number: 'D076', door_range_id: '19')
Door.create(number: 'D077', door_range_id: '20')
Door.create(number: 'D078', door_range_id: '20')
Door.create(number: 'D079', door_range_id: '20')
Door.create(number: 'D080', door_range_id: '21')
Door.create(number: 'D081', door_range_id: '21')
Door.create(number: 'D082', door_range_id: '21')
Door.create(number: 'D083', door_range_id: '22')
Door.create(number: 'D084', door_range_id: '22')
Door.create(number: 'D085', door_range_id: '22')
Door.create(number: 'D086', door_range_id: '23')
Door.create(number: 'D087', door_range_id: '23')
Door.create(number: 'D088', door_range_id: '23')
Door.create(number: 'D089', door_range_id: '24')
Door.create(number: 'D090', door_range_id: '24')
Door.create(number: 'D091', door_range_id: '24')
Door.create(number: 'D092', door_range_id: '25')
Door.create(number: 'D093', door_range_id: '25')
Door.create(number: 'D094', door_range_id: '25')
Door.create(number: 'D095', door_range_id: '26')
Door.create(number: 'D096', door_range_id: '26')
Door.create(number: 'D097', door_range_id: '26')
# Door.create(number: 'D098', door_range_id: ) # not used due to death 
Door.create(number: 'D099', door_range_id: '27')
Door.create(number: 'D100', door_range_id: '27')
Door.create(number: 'D101', door_range_id: '28')
Door.create(number: 'D102', door_range_id: '28')
Door.create(number: 'D103', door_range_id: '28')
Door.create(number: 'D104', door_range_id: '29')
Door.create(number: 'D105', door_range_id: '29')
Door.create(number: 'D106', door_range_id: '29')
Door.create(number: 'D107', door_range_id: '29')
Door.create(number: 'D108', door_range_id: '30')
Door.create(number: 'D109', door_range_id: '30')
Door.create(number: 'D110', door_range_id: '30')
Door.create(number: 'D111', door_range_id: '31')
Door.create(number: 'D112', door_range_id: '31')
Door.create(number: 'D113', door_range_id: '31')
Door.create(number: 'D114', door_range_id: '31')
Door.create(number: 'D115', door_range_id: '32')
Door.create(number: 'D116', door_range_id: '32')